-- Canonical seed data for the Node/Express API.
-- Apply this through:
-- supabase/seed.sql
--
-- The Supabase seed file includes app-wide seeded profiles, groups, expenses,
-- gifts, community savings records, notifications, and activity logs.
